blankissuesenabled: 
contactlinks:
   name: New license request via SPDX Online 
    url: https://spdx.org/app/submit_new_license/
    about: Preferred way to request a license, so that it appears on https://spdx.org/app/license_requests/
